os: linux
dist: xenial
language: python
python: 3.7
fast_finish: true

env:
    GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/.gcloud-credentials.json

before_install:
  - openssl aes-256-cbc -K $encrypted_291608e092e6_key -iv $encrypted_291608e092e6_iv -in .gcloud-credentials.json.enc -out .gcloud-credentials.json -d

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        python3 -m venv venv
        source venv/bin/activate
    fi
  - pip install -e ".[test]"

script:
  - bash tests.sh
  - pytest --cov=tsd --cov-report term-missing

jobs:
  include:
    - stage: test
    - stage: test
      os: osx
      language: generic

    - stage: deploy
      if: tag IS present AND repo = glostis/tsd
      before_install: skip
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: glostis
          password:
            secure: "UnfW1N/gQESCSbnZchLixVAHVecwJHYoEGgfmW2JzTc4OJWSsTxF2MUYnb81qSfkxkXh3RF+VieShfVkjfhwhAmUXbbcYd2gvH+5D5i+XehGdXiXZYjYwm/mDEUPczUgVelVgq6unLRSey5CarfsfBUZczaJfZjaVBZnOzbI7iP3GnIbufiSF6HTvfTXgvbMf6j7XS1IsjEE/n7rpt2ixFiT45Tk2X2KyLbmOxk98WKfNqBU55wuQZ/EfbvG7rU/xhYNTImRv2fa9SjJOu8WuYYlC/MQIn7uID5kXdAqTlbIqxFrpxcPohTEvp+HJakcdCzyohL4B1G61nC3/gd24FGnsPswpvGQIiL3aQRDdMB43BX3jVmUOzIzpEDmI9Qrq1g4F+Eu9EuGwgIT/Lk5q/0RHFu5YpqhBVQKtu2UN441kuc5XS5x07aB/AAg/t3Yq1hdF4goZ0cRrBugN4J+fZhyX0WOpFkT/Z/2hiQgo83uR77+ovWi8s4DO3syFWCoP9hItTNRrvDuB/KV1dpGieyghlOqAnzV1vW3Bek99KxZksQqQGTzQ6mH3a436LaCnNuBEGDGANeHf3OUc9XjsuQR3hxz5Rhh9t74Qjld8E5yGAtM5NiIm9i6z5k6xsWy19rI2sV315i3yLKVWqaiCIMztuqbS+MuWzL8+Bsuo14="
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel
          on:
            tags: true
